Django/myproject/myApp/urls.py
from django.conf.urls import url
# from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # url('^$', views.index, name="index"),
    url('^$', views.index, name="index"),
    url(r'index.html', views.index1),
    # path(r'', views.index),
    # path('<int:num>/', views.detail)
    # url(r'^(\d+)/$', views.vote),
    url(r'^(\d+)/$', views.vote),
    url(r'^(\d+)/(\d+)/$', views.detail),
    url(r'^grades/$', views.grades),
    url(r'^grades2/$', views.grades2),
    url(r'^students/$', views.students),
    url(r'^students2/$', views.students2),
    url(r'^students3/$', views.students3),
    url(r'^students/(\d+)/$', views.stupage),
    url(r'^studentsearch/$', views.studentsearch),
    url(r'^grades/(\d+)/$', views.gradesStudents),
    url(r'^grades2/(\d+)/$', views.gradesStudents),
    url(r'^addstudent/$', views.addstudent),
    url(r'^addstudent2/$', views.addstudent2),

    url(r'^attribute/$', views.attribute),
    url(r'^get1/$', views.get1),
    url(r'^get2/$', views.get2),

    url(r'^showregist/$', views.showregist),
    url(r'^showregist/regist/$', views.regist),

    url(r'^showresponse/$', views.showresponse),
    url(r'^cookietest/$', views.cookietest),

    url(r'^redirect1/$', views.redirect1),
    url(r'^redirect2/$', views.redirect2),

    # url(r'homepage/$', views.homepage) 也是可以的
    url(r'^homepage/$', views.homepage),
    url(r'^login/$', views.login),
    url(r'^showhomepage/$', views.showhomepage),
    url(r'^quit/$', views.quit),

    url(r'^getstudent/$', views.getstudent),

    url(r'^good/(\d+)/(\d+)$', views.good, name="good"),

    url(r'^main/$', views.main),
    url(r'^detail2/$', views.detail2),

    url(r'^postfile/$', views.postfile),
    url(r'^showinfo/$', views.showinfo),

    url(r'^captcha/$', views.captcha),
    url(r'^captchafile/$', views.captchafile),
    url(r'^verifycaptcha/$', views.verifycaptcha),

    url(r'^uploadfile/$', views.uploadfile),
    url(r'^savefile/$', views.savefile),

    url(r'^studentpage/(\d+)/$', views.studentpage),

    url(r'^edit/$', views.edit),

    url(r'^celery/$', views.celery),

    url(r'^login2/$', views.Login.as_view()),
]

Django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^', include('myApp.urls'))
    # 此版本不适用这种方法，须在对应app目录下的url.py文件中添加一行代码：app_name = 'app'，这种方法来命名app
    # url('', include('myApp.urls', namespace="app"))
    # url('', include('myApp.urls'))
    url('sunck/', include('myApp.urls'))
    # path('', include('myApp.urls'))
]

Django/myproject/myApp/models.py
from django.db import models


# 一个模型类在数据库中对应一张数据表
# 使用模型类进行增删改查操作
# Create your models here.
# 不用创建主键，会自动生成且递增
class Grades(models.Model):
    gname = models.CharField(max_length=20)
    gdate = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum = models.IntegerField()
    isDelete = models.BooleanField(default=False)

    # admin后台将每个Grades对象显示为：Grades object
    # 解决：重写__str__方法
    def __str__(self):
        # return "%s-%d-%d" % (self.gname, self.ggirlnum, self.gboynum)
        return self.gname

    # 模型的元数据即“所有不是字段的东西”，比如排序选项（ ordering ），数据库表名（ db_table，这些都不是必须的
    # class Meta:
    #     # ordering = ['id']
    #     db_table = "grades"


# 自定义管理器 `Manager`类
# 修改管理器返回的原始查询集， 重写get_quertset()方法
class StudentsManager(models.Manager):
    def get_queryset(self):
        return super(StudentsManager,
                     self).get_queryset().filter(isDelete=False)

    def createStudents(self, name, age, gender, content, grade, isD=False):
        # 创建一个Students对象
        stu = self.model()
        # print(stu)
        # print(type(stu))
        stu.sname = name
        stu.sage = age
        stu.sgender = gender
        stu.scontent = content
        stu.sgrade = grade
        return stu


class Students(models.Model):
    # 自定义模型管理器
    stuObject = models.Manager()
    stuObject2 = StudentsManager()
    # 没有定义模型管理器时，获取所有Students对象：Students.objects.all()
    # 定义后 Students.stuObject2.all()
    sname = models.CharField(max_length=20)
    sgender = models.BooleanField(default=True)
    sage = models.IntegerField()
    # sage = models.IntegerField(do_column="age")
    scontent = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)
    # 关联外键
    sgrade = models.ForeignKey("Grades", on_delete=models.CASCADE)

    # python manage.py shell中操作
    # Students对象sgrade赋值
    # s = Students()
    # g = Grades()
    # s.sgrade = g
    # 保存数据：s.save()
    def __str__(self):
        return self.sname

    # lastTime = models.DateTimeField(auto_now=True)
    # createTime = models.DateTimeField(auto_created=True)
    # class Meta:
    #     # ordering = ['id']
    #     db_table = "students"

    # 定义一个类方法创建对象，添加@classmethod 表明以下方法为类方法
    # 不加@classmethod，def createStudents(Students):
    @classmethod
    def createStudents(cls, name, age, gender, content, grade, isD=False):
        stu = cls(sname=name,
                  sage=age,
                  sgender=gender,
                  scontent=content,
                  sgrade=grade,
                  isDelete=isD)
        return stu

    def getName(self):
        return self.sname


from tinymce.models import HTMLField


class Text(models.Model):
    str = HTMLField()

Django/myproject/myApp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index1(request):  # request 浏览器请求
    # return HttpResponse("sunk is good man!")  # HttpResponse 浏览器响应
    return HttpResponseRedirect('/sunck')


def index(request):
    return render(request, 'myApp/index.html')


# 在浏览器地址输入栏中传参数num，只需在原有url后面添加新的内容，如'3/'或'3'
def vote(request, num):
    return HttpResponse("detail-%s" % (num))


def detail(request, num1, num2):
    return HttpResponse("detail-%s-%s" % (num1, num2))


from .models import Grades, Students


def grades(request):
    # 去模板里取数据
    gradesList = Grades.objects.all()
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回浏览器
    return render(request, 'myApp/grades.html', {'grades': gradesList})


from django.db.models import F, Q


def grades2(request):
    # 描述中带有“hua”的数据对应的班级
    gradesList = Grades.objects.filter(students__scontent__contains="hua")
    # gradesList = Grades.objects.filter(ggirlnum__lt=F('gboynum') - 50)
    return render(request, 'myApp/grades.html', {'grades': gradesList})


def students(request):
    # 返回包含所有 Students 对象的列表
    # studentsList = Students.objects.all()
    studentsList = Students.stuObject2.all()
    return render(request, 'myApp/students.html', {'students': studentsList})


def students2(request):
    # 返回包含所有 Students 对象的列表
    # studentsList = Students.objects.all()
    # 报异常，可以考虑添加try，或者换成filter()方法
    # studentsList = Students.stuObject2.get(sgender=0)
    studentsList = Students.stuObject2.all()
    return render(request, 'myApp/students2.html', {'students': studentsList})


# 显示前5条学生
def students3(request):
    studentsList = Students.stuObject2.all()[0:5]
    return render(request, 'myApp/students.html', {'students': studentsList})


# 分页显示学生
def stupage(request, page):
    # 0-5 5-10
    #  1   2
    page = int(page)
    studentsList = Students.stuObject2.all()[((page - 1) * 5):(page * 5)]
    return render(request, 'myApp/students.html', {'students': studentsList})


from django.db.models import Max


def studentsearch(request):
    # studentsList = Students.stuObject2.filter(pk__in=[2, 6, 7])
    # maxAge = Students.stuObject2.aggregate(Max("sage"))
    # print(maxAge)
    # studentsList = Students.stuObject2.filter(Q(pk__lte=3) | Q(sage__lt=23))
    studentsList = Students.stuObject2.filter(~Q(pk__lte=3))
    return render(request, 'myApp/students.html', {'students': studentsList})


def gradesStudents(request, num):
    # 获取指定班级的学生
    grade = Grades.objects.get(pk=num)
    studentsList = grade.students_set.all()
    return render(request, 'myApp/students.html', {'students': studentsList})


def addstudent(request):
    grade = Grades.objects.get(pk=1)
    stu = Students.createStudents("刘德华", 34, True, "my name is hua", grade)
    stu.save()
    return HttpResponse("fadfa")


def addstudent2(request):
    grade = Grades.objects.get(pk=1)
    stu = Students.stuObject2.createStudents("李华", 32, True, "hello world",
                                             grade)
    stu.save()
    return HttpResponse("****")


def attribute(request):
    print(request.path)
    print(request.method)
    print(request.encoding)
    print(request.GET)
    print(request.POST)
    print(request.FILES)
    print(request.COOKIES)
    print(request.session)
    return HttpResponse("attribute")


def get1(request):
    # a = request.GET.get['a']
    a = request.GET.get('a')
    b = request.GET.get('b')
    c = request.GET.get('c')
    # print(type(a))
    return HttpResponse(a + ' ' + b + ' ' + c)


def get2(request):
    a = request.GET.getlist('a')
    a1 = a[0]
    a2 = a[1]
    c = request.GET.get('c')
    return HttpResponse(a1 + ' ' + a2 + ' ' + c)


# POST
def showregist(request):
    return render(request, 'myApp/regist.html')


def regist(request):
    name = request.POST.get('name')
    gender = request.POST.get('gender')
    age = request.POST.get('age')
    hobby = request.POST.getlist('hobby')
    print(name)
    print(gender)
    print(age)
    print(hobby)
    return HttpResponse("post")


# response
def showresponse(request):
    res = HttpResponse()
    res.content = b'good'
    print(res.content)
    print(res.charset)
    print(res.status_code)
    print(res.content - type)
    return res


# cookie
def cookietest(request):
    res = HttpResponse()
    # cookie = res.set_cookie('sunck', 'good')
    cookie = request.COOKIES
    res.write("<h1>" + cookie['sunck'] + "</h1>")
    return res


# 重定向
from django.http import HttpResponseRedirect
from django.shortcuts import redirect


def redirect1(request):
    # return HttpResponseRedirect('/sunck/redirect2')
    return redirect('/sunck/redirect2')


def redirect2(request):
    return HttpResponse("<h1>我是重定向后的视图</h1>")


# session
def homepage(request):
    # 取session
    # username = "游客"
    username = request.session.get('name', "游客")
    return render(request, 'myApp/homepage.html', {'username': username})


def login(request):
    return render(request, 'myApp/login.html')


def showhomepage(request):
    username = request.POST.get('username')
    # 存储session
    request.session['name'] = username
    # request.session.set_expiry(10)
    return redirect('/sunck/homepage/')


from django.contrib.auth import logout


def quit(request):
    # 清除session,推荐使用logout(request)
    logout(request)
    # request.session.clear()
    # request.session.flush()
    return redirect('/sunck/homepage/')


# 模板语法
def getstudent(request):
    student = Students.stuObject2.get(pk=1)
    return render(
        request, 'myApp/index2.html', {
            'stu': student,
            'num': 10,
            'str': 'sunck is good man',
            'list': ['sunck', 'good', 'man'],
            'test': False,
            'code': '<h2>sunck is good!</h2>'
        })


# 反向解析
def good(request, num1, num2):
    return render(request, 'myApp/good.html', {'num1': num1, 'num2': num2})


# 模板继承
def main(request):
    return render(request, 'myApp/main.html')


def detail2(request):
    return render(request, 'myApp/detail.html')


# CSRF
def postfile(request):
    return render(request, 'myApp/postfile.html')


def showinfo(request):
    username = request.POST.get('username')
    print(username)
    password = request.POST.get('passwd')
    print(password)
    return render(request, 'myApp/showinfo.html', {
        'username': username,
        'password': password
    })


# 验证码
def captcha(request):
    import os
    import random
    # import base64
    from io import BytesIO
    from PIL import Image
    from PIL import ImageDraw
    from PIL import ImageFont

    def random_color():
        c1 = random.randint(0, 255)
        c2 = random.randint(0, 255)
        c3 = random.randint(0, 255)
        return c1, c2, c3

    def generate_picture(width=120, height=35):
        image = Image.new('RGB', (width, height), random_color())
        return image

    def random_str():
        '''
        获取一个随机字符, 数字或小写字母
        :return:
        '''
        random_num = str(random.randint(0, 9))
        random_low_alpha = chr(random.randint(97, 122))
        random_char = random.choice([random_num, random_low_alpha])
        return random_char

    def draw_str(count, image, font_size):
        """
        在图片上写随机字符
        :param count: 字符数量
        :param image: 图片对象
        :param font_size: 字体大小
        :return:
        """
        draw = ImageDraw.Draw(image)
        # 获取一个font字体对象参数是ttf的字体文件的目录，以及字体的大小
        font_file = r'C:\Windows\Fonts\Adobe Arabic\AdobeArabic-Regular.otf'
        font = ImageFont.truetype(font_file, size=font_size)
        temp = []
        for i in range(count):
            random_char = random_str()
            draw.text((10 + i * 30, -2),
                      random_char,
                      random_color(),
                      font=font)
            temp.append(random_char)

        valid_str = "".join(temp)  # 验证码
        return valid_str, image

    def noise(image, width=120, height=35, line_count=3, point_count=20):
        '''

        :param image: 图片对象
        :param width: 图片宽度
        :param height: 图片高度
        :param line_count: 线条数量
        :param point_count: 点的数量
        :return:
        '''
        draw = ImageDraw.Draw(image)
        for i in range(line_count):
            x1 = random.randint(0, width)
            x2 = random.randint(0, width)
            y1 = random.randint(0, height)
            y2 = random.randint(0, height)
            draw.line((x1, y1, x2, y2), fill=random_color())

            # 画点
            for i in range(point_count):
                draw.point(
                    [random.randint(0, width),
                     random.randint(0, height)],
                    fill=random_color())
                x = random.randint(0, width)
                y = random.randint(0, height)
                draw.arc((x, y, x + 4, y + 4), 0, 90, fill=random_color())

        return image

    image = generate_picture()
    valid_str, image = draw_str(4, image, 35)
    request.session['captcha'] = valid_str
    # print(valid_str)
    # print(type(valid_str))
    image = noise(image)

    f = BytesIO()
    image.save(f, 'png')  # 保存到BytesIO对象中, 格式为png
    return HttpResponse(f.getvalue(), 'image/png')


def captchafile(request):
    flag = request.session.get('flag', 'True')
    str = ''
    if flag == False:
        str = '请重新输入'
    request.session.clear()
    return render(request, 'myApp/captchafile.html', {'flag': str})


def verifycaptcha(request):
    code1 = request.POST.get('verifycaptcha').upper()
    code2 = request.session['captcha'].upper()
    if code1 == code2:
        return render(request, 'myApp/success.html')
    else:
        request.session['flag'] = False
        return redirect('/sunck/captchafile/')


# 文件上传
def uploadfile(request):
    return render(request, 'myApp/uploadfile.html')


import os
from django.conf import settings


def savefile(request):
    # print("****")
    # print(request.method)
    # print(request.FILES)

Django/myproject/templates/myApp/ajaxstudent.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Ajax</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>学生信息列表</h1>
        <button id="btn">显示学生信息</button>
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            #header{
                width: 100px;
                height: 100px;
                background-color: red;
            }
            #footer{
                width: 100px;
                height: 100px;
                background-color: blue;
            }
        </style>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div id="header">header</div>
        <div id="main">
            {% block main %}

            {% endblock main %}
            <hr>
            {% block main2 %}

            {% endblock main2 %}
        </div>

        <div id="footer">footer</div>
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/celery.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Celery</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>我是celery页面</h1>
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/edit.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>富文本</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <script type="tex/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
        <script type="tex/javascript">
            tinyMCE.init({
                'mode':'textareas',
                'theme':'advanced'
                'width':800,
                'height':600,
            })
        </script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <form action="/sunck/saveblog/">
            <textarea name="str" id="" cols="30" rows="10">sunck is good man</textarea>
            <input type="submit" value="提交">
        </form>
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>主页</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="stylesheet" type="text/css" href="/static/myApp/css/style.css"> -->
        <style>
            h1{
                color: red;
            }
        </style>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>index页面</h1>
        <h1>sunck is good!</h1>
        <a href="/sunck/good/">链接1</a>
        <a href="{% url 'app:good' 123 456%}">链接2</a>
        <!-- <img src="/static/myApp/img/captcha.png" alt=""> -->
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/index2.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>主页</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>index页面</h1>
        <h1>{{stu.sname}}</h1>
        <h1>{{stu.getName}}</h1>
        <h1>num = {{num}}</h1>
        {% if num %}
            <h2>sunck is good!</h2>
        {% endif %}

        {% ifequal 'sunck' 'sunck' %}
            <!-- 值1和值2相等时执行下面语句 -->
            <h1>Welcome!</h1>
        {% endifequal %}

        {% ifnotequal 'sunck' 'kai' %}
            <!-- 值1和值2相等时执行下面语句 -->
            <h1>Not welcome!</h1>
        {% endifnotequal %}

        <h2>{{str|upper}}</h2>

        {# 这是一个注释 #}

        {% comment %}
            <h1>comment测试</h1>
            <h1>comment语法</h1>
            {{stu.sname}}
        {% endcomment%}

        <h2>{{list|join:'#'}}</h2>
        <h2>{{test|default:'没有'}}</h2>

        <h2>{{num}}</h2>
        <h2>{{num|add:10}}</h2>
        <h2>{{num|add:-10}}</h2>
        <!-- num/1*5 -->
        <!-- num*5 -->
        <h2>{% widthratio num 1 5%}</h2>
        <!-- num/5 -->
        <h2>{% widthratio num 5 1%}</h2>


        {{code}}
        {{code|escape}}
        {{code|safe}}

        {% autoescape off%}
        {{code}}
        {% endautoescape %}
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/main.html
{% extends 'myApp/base.html' %}

{% block main %}
    <h1>sunck is good man</h1>
{% endblock main %}

Django/myproject/templates/myApp/postfile.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>个人档案</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <form action="/sunck/showinfo/" method="POST">
            {% csrf_token %}
            姓名：<input type="text" name="username"/>
            <hr>
            密码：<input type="password" name="passwd"/>
            <hr>
            <input type="submit" value="登录"/>
        </form>
        <script src="" async defer></script>
    </body>
</html>

Django/myproject/templates/myApp/regist.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>注册</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <form action="regist/" method="post">
            姓名：<input type="text" name="name" value="">
            <hr>
            性别：<input type="radio" name="gender" value="1">男<input type="radio" name="gender" value="0">女
            <hr>
            年龄：<input type="tex" name="age" value="">
            <hr>
            爱好：<input type="checkbox" name="hobby" value="power">权力<input type="checkbox" name="hobby" value="money">金钱<input type="checkbox" name="hobby" value="ball">篮球
            <hr>
            <input type="submit" name="" value="注册">
        </form>
        
        <script src="" async defer></script>
    </body>
</html>