练手项目/fruitShop/fruitShop/urls.py
# coding=utf-8

from django.conf.urls import url
import views
from views import *

urlpatterns = [
    url(r'^user/register$', views.user_register, name='user_register'),
    url(r'^user/user_exist$', views.user_exist, name='user_exist'),
    url(r'^user/login$', views.user_login, name='user_login'),
    url(r'^user/info$', views.user_info, name='user_info'),
    url(r'^user/order/(\d*)$', views.user_order, name='user_order'),
    url(r'^user/site$', views.user_site, name='user_site'),
    url(r'^user/logout', views.user_logout, name='user_logout'),

    url(r'^$', views.index, name='index'),
    url(r'^list/(\d+)/(\d*)/(\d*)$', views.list, name='list'),
    url(r'^detail/(\d+)$', views.detail, name='detail'),

    url(r'^mycart$', views.cart, name='cart'),
    url(r'^addcart$', views.addCart, name='addcart'),
    url(r'^getcartcount$', views.getMyCartCount, name='getcartcount'),
    url(r'^editcart$', views.editCartGood, name='editcart'),
    url(r'^revieworder$', views.reviewOrder, name='revieworder'),
    url(r'^orderhandle$', views.orderHandle, name='orderhandle'),
    url(r'^pay/(\d+)$', views.pay, name='pay'),
    url(r'^search/',MySearchView())
]

练手项目/fruitShop/myShop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('fruitShop.urls',namespace='fruitShop')),
    url(r'^tinymce',include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
]

练手项目/fruitShop/fruitShop/models.py
# coding=utf-8
from django.db import models
from tinymce.models import HTMLField


# 用户模型
class UserInfo(models.Model):
    nickname = models.CharField(max_length=10)
    password = models.CharField(max_length=40)
    email = models.CharField(max_length=30)
    phone = models.CharField(max_length=11, default='')
    # 收件人
    shou_people = models.CharField(max_length=10, default='')
    # 收货地址,省,市,县,具体地址
    p_c_a_detail = models.CharField(max_length=100, default='')
    # 邮编
    zip_code = models.IntegerField(default=0)


# 商品分类
class GoodsCategory(models.Model):
    title = models.CharField(max_length=10)
    # 封面
    cover = models.ImageField(upload_to='category')
    # css 类名
    className = models.CharField(max_length=10, default='')
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.title.encode('utf-8')


# 商品
class GoodsInfo(models.Model):
    name = models.CharField(max_length=20)
    picture = models.ImageField(upload_to='goods')
    # 单位
    unit = models.CharField(default='500g', max_length=20)
    # 点击数,热度
    click = models.IntegerField(default=0)
    # 简介
    intro = models.CharField(max_length=200)
    number = models.IntegerField(default=0)
    # 介绍
    content = HTMLField()
    # 分类
    category = models.ForeignKey(GoodsCategory)
    # 价格
    price = models.DecimalField(max_digits=5, decimal_places=2)
    # 推荐
    isTop = models.BooleanField(default=False)
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.name.encode('utf-8')


# 首页banner
class Banner(models.Model):
    title = models.CharField(max_length=20)
    banner = models.ImageField(upload_to='banner')
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.title.encode('utf-8')


# 订单表
class OrderInfo(models.Model):
    # 订单号
    id = models.CharField(max_length=30, primary_key=True)
    # 用户
    user = models.ForeignKey(UserInfo)
    # 日期
    date = models.DateTimeField(auto_now=True)
    # 是否支付
    isPay = models.BooleanField(default=False)
    # 支付金额
    totalPrice = models.DecimalField(max_digits=6, decimal_places=2)
    # 收货地址
    address = models.CharField(max_length=100, default='')


# 订单详情表
class OrderDetail(models.Model):
    # 商品
    goods = models.ForeignKey(GoodsInfo)
    # 订单
    order = models.ForeignKey(OrderInfo)
    # 单价
    price = models.DecimalField(max_digits=5, decimal_places=2)
    # 数量
    number = models.IntegerField(default=0)


# 购物车
class ShopCart(models.Model):
    user = models.ForeignKey(UserInfo)
    good = models.ForeignKey(GoodsInfo)
    number = models.IntegerField(default=0)

练手项目/fruitShop/fruitShop/views.py
# coding=utf-8
from django.shortcuts import render, redirect
from models import *
from hashlib import sha1
from django.http import JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import *
from decorators import *
from django.db.models import Sum
from django.db import transaction
import datetime
from decimal import Decimal
from haystack.views import SearchView


# 用户注册
def user_register(request):
    if request.method == 'POST':
        # 接受用户输入
        user_name = request.POST.get('user_name')
        email = request.POST.get('email')
        pwd = request.POST.get('pwd')
        cpwd = request.POST.get('cpwd')
        # 判断两次密码是否相等
        if pwd != cpwd:
            return redirect(reverse('fruitShop:user_register'))
        # 密码加密
        s1 = sha1()
        s1.update(cpwd)
        password = s1.hexdigest()
        # 保存数据
        UserInfo.objects.create(nickname=user_name, password=password, email=email)
    return render(request, 'fruitShop/user/register.html', {'title': '用户注册'})


# 检测用户名时候已存在
def user_exist(request):
    if request.is_ajax():
        nickname = request.GET.get('nickname')
        count = UserInfo.objects.filter(nickname=nickname).count()
        return JsonResponse({'count': count})


# 用户登录
def user_login(request):
    if request.method == 'POST':
        nickname = request.POST.get('username', '')
        password = request.POST.get('pwd', '')
        remember = request.POST.get('remember', 0)
        # 查询用户是否存在
        user = UserInfo.objects.filter(nickname=nickname)
        if len(user) == 1:
            s1 = sha1()
            s1.update(password)
            if s1.hexdigest() == user[0].password:
                # 密码验证成功
                to_url = request.COOKIES.get('to_url', '/')
                redirect = HttpResponseRedirect(to_url)
                if remember:
                    # 记住用户名
                    redirect.set_cookie('nickname', nickname)

                # 保存session用户信息
                request.session['user_id'] = user[0].id
                request.session['nickname'] = nickname
                # 进行跳转
                return redirect
            else:
                context = {'nickname_error': '', 'password_error': '密码错误', 'nickname': nickname, 'pwd': password}
        else:
            context = {'nickname_error': '用户名不存在', 'password_error': '', 'nickname': nickname, 'pwd': password}
        return render(request, 'fruitShop/user/login.html', context)
    nickname = request.COOKIES.get('nickname', '')
    return render(request, 'fruitShop/user/login.html',
                  {'nickname_error': '', 'password_error': '', 'nickname': nickname, 'pwd': '', 'title': '用户登录'})


# 退出登录
def user_logout(request):
    request.session.flush()
    return redirect('/')


# 用户信息
@check_user_login
def user_info(request):
    good_ids = request.COOKIES.get('good_ids', '')
    if good_ids != '':
        good_ids_list = good_ids.split(',')
    else:
        good_ids_list = []
    viewGoods = GoodsInfo.objects.filter(id__in=good_ids_list)
    user_id = request.session.get('user_id', 0)
    user = UserInfo.objects.filter(pk=user_id)
    context = {'userInfo': user[0], 'title': '用户中心-个人信息', 'viewGoods': viewGoods, 'user_p_title': '用户中心'}
    return render(request, 'fruitShop/user/info.html', context)


# 用户订单
@check_user_login
def user_order(request, p):
    if p == '':
        p = 1
    user_id = request.session.get('user_id')
    orders = OrderInfo.objects.filter(user_id=user_id).order_by('-id')
    orderDetails = []
    for order in orders:
        detail = OrderDetail.objects.filter(order_id=order.id)
        order.detail = detail
        orderDetails.append(order)
    print(orderDetails)
    paginator = Paginator(orderDetails, 3)
    page = paginator.page(int(p))
    context = {'title': '用户中心-订单', 'user_p_title': '用户中心', 'page': page, 'p_index': p}
    return render(request, 'fruitShop/user/order.html', context)


# 用户收货地址
@check_user_login
def user_site(request):
    user_id = request.session.get('user_id', 0)
    user = UserInfo.objects.filter(pk=user_id)[0]
    if request.method == 'POST':
        shou_people = request.POST.get('shou_people')
        phone = request.POST.get('phone')
        zip_code = request.POST.get('zip_code')
        user.shou_people = shou_people
        user.phone = phone
        user.p_c_a_detail = request.POST.get('address', '')
        if zip_code == '':
            zip_code = 0
        user.zip_code = zip_code
        user.save()
    context = {'title': '用户中心-收货地址', 'userInfo': user, 'user_p_title': '用户中心'}
    return render(request, 'fruitShop/user/site.html', context)


# 首页
def index(request):
    # 所有的分类
    categories = GoodsCategory.objects.all()[:6]
    data = []
    for cate in categories:
        # 根据分类查询商品
        this_good = cate.goodsinfo_set
        if len(this_good.order_by('-click')) > 0:
            data.append({
                'cate': cate,  # 分类
                'goods': this_good.order_by('-click')[:4],  # 分类下的商品
                's_goods': this_good.filter(isTop=1).values('id', 'name')[:4]
            })
    banners = Banner.objects.all()
    context = {'title': '商城首页', 'categories': categories, 'data': data, 'banners': banners}
    return render(request, 'fruitShop/index.html', context)


# 商品列表
def list(request, c_id, p_index, sort):
    cates = __getCategory()
    newGoods = GoodsInfo.objects.filter(category_id=c_id).order_by('-id')[:5]
    if sort == '2':
        sort_by = 'price'
    elif sort == '3':
        sort_by = '-click'
    else:
        sort_by = 'id'
    goods = GoodsInfo.objects.filter(category_id=c_id).order_by(sort_by)
    paginator = Paginator(goods, 30)
    page = paginator.page(int(p_index))
    context = {
        'title': '商品列表',
        'c_id': c_id,
        'sort': sort,
        'page': page,
        'categories': cates,
        'newGoods': newGoods
    }
    return render(request, 'fruitShop/list.html', context)


# 商品详情
def detail(request, id):
    cates = __getCategory()
    good = GoodsInfo.objects.filter(pk=id)[0]
    good.click += 1
    good.save()
    t_goods = GoodsInfo.objects.filter(category_id=good.category_id)[:3]
    cate = GoodsCategory.objects.filter(pk=good.category_id)[0].title
    # 添加商品浏览记录
    good_ids = request.COOKIES.get('good_ids', '')
    good_id = '%d' % good.id
    if good_ids != '':
        good_ids_list = good_ids.split(',')
        # 如果没有就插入一个
        if good_ids_list.count(good_id) == 0:
            good_ids_list.insert(0, good_id)
        if len(good_ids_list) > 5:
            # 删除最后一个
            del good_ids_list[5]
        good_ids = ','.join(good_ids_list)
    else:
        # 添加第一条
        good_ids = good_id
    context = {
        'title': '商品详情',
        'categories': cates,
        'id': id,
        'good': good,
        'cate': cate,
        't_goods': t_goods
    }
    responce = render(request, 'fruitShop/detail.html', context)
    # 保存浏览历史到cookie
    responce.set_cookie('good_ids', good_ids)
    return responce


# 获取分类
def __getCategory():
    categories = GoodsCategory.objects.filter(isDelete=0)
    cates = []
    for cate in categories:
        if len(cate.goodsinfo_set.all()) > 0:
            cates.append(cate)
    return cates


# 购物车
@check_user_login
def cart(request):
    user_id = request.session.get('user_id')
    cartGoods = ShopCart.objects.filter(user_id=user_id)
    context = {'title': '我的购物车', 'cartGoods': cartGoods, 'user_p_title': '我的购物车'}
    return render(request, 'fruitShop/cart.html', context)


# 添加商品到购物车
def addCart(request):
    user_id = request.session.get('user_id', '')
    if user_id == '':
        return JsonResponse({'status': 0, 'msg': '您未登录'})
    else:
        good_id = request.POST.get('id', 0)
        goods_number = GoodsInfo.objects.get(pk=good_id).number
        number = int(request.POST.get('number', 1))
        if goods_number >= number:
            this_goods = ShopCart.objects.filter(good_id=good_id)
            if len(this_goods) == 1:
                this_good = this_goods[0]
                this_good.number += number
                this_good.save()
            else:
                ShopCart.objects.create(user_id=user_id, number=1, good_id=good_id)
            return JsonResponse({'status': 1, 'msg': '添加成功'})
        else:
            return JsonResponse({'status': 3, 'msg': '库存不足'})


# 获取购物车数量
def getMyCartCount(request):
    user_id = request.session.get('user_id', '')
    if user_id == '':
        return JsonResponse({'count': 0})
    else:
        count = ShopCart.objects.filter(user_id=user_id).aggregate(Sum('number'))
        return JsonResponse({'count': count['number__sum']})


# 编辑购物车
@check_user_login
def editCartGood(request):
    id = request.POST.get('id', 0)
    if request.POST.get('delete', 0) == '1':
        this_chart_good = ShopCart.objects.get(pk=id)
        this_chart_good.delete()
        return JsonResponse({'status': 1, 'msg': '删除完成'})
    if request.POST.get('number', 0) != 0:
        number = request.POST.get('number', 0)
        this_chart_good = ShopCart.objects.get(pk=id)
        this_chart_good.number = number
        this_chart_good.save()
        return JsonResponse({'status': 1, 'msg': '修改完成'})


# 预览订单
@check_user_login
def reviewOrder(request):
    address = UserInfo.objects.get(pk=request.session.get('user_id')).p_c_a_detail
    context = {'address': address, 'title': '确认订单', 'user_p_title': '确认订单'}
    cart_ids = request.GET.getlist('selectme')
    carts = ShopCart.objects.filter(id__in=cart_ids)
    context['carts'] = carts
    context['cart_ids'] = '_'.join(cart_ids)
    return render(request, 'fruitShop/review_order.html', context)


# 启用数据库事务操作
@transaction.atomic()
@check_user_login
def orderHandle(request):
    # 记录当前操作点
    tran_id = transaction.savepoint()
    # /接受要支付的购物车id
    cart_ids = request.GET.get('cart_ids')
    try:
        order = OrderInfo()
        now = datetime.datetime.now()

练手项目/fruitShop/templates/fruitShop/base_buttom_top.html
{% extends 'fruitShop/base_buttom.html' %}
{% block body %}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.user_id %}
				<div class="login_info fl" style="display: block">
					欢迎您：<em>{{ request.session.nickname }}</em>
				</div>
                <div class="user_link fl">
					<span>|</span>
					<a href="{% url 'fruitShop:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'fruitShop:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'fruitShop:user_order' 1 %}">我的订单</a>
                <div class="login_btn fl">
					<span>|</span>
					<a href="{% url 'fruitShop:user_logout' %}">退出</a>
				</div>
				</div>
                    {% else %}
                    <div class="login_btn fl">
					<a href="{% url 'fruitShop:user_login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'fruitShop:user_register' %}">注册</a>
				</div>
                {% endif %}
			</div>
		</div>
	</div>
    {% block body_content %}

        {% endblock %}
{% endblock %}

练手项目/fruitShop/templates/fruitShop/base_goods.html
{% extends 'fruitShop/base_buttom_top.html' %}
{% block body_content %}
{#    index.detail,list公用模板#}
{% load static %}
    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'fruitShop/images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
			<input type="text" class="input_text fl" name="q" value="{{ query }}" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" value="搜索">
                </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'fruitShop:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
    {% block body_content_inner %}

        {% endblock %}
    <script>
    getMyChartCount();
    function getMyChartCount() {
        $.post('{% url 'fruitShop:getcartcount' %}',
            {'csrfmiddlewaretoken':'{{ csrf_token }}'},
            function(res){
                $("#show_count").html(res.count)
        })
    }
    function addCart(good_id) {
        $.post('{% url 'fruitShop:addcart' %}',
            {'id':good_id,'csrfmiddlewaretoken':'{{ csrf_token }}'},
            function(res){
                if(res.status==1){
                    getMyChartCount()
                }else if(res.status==3){
                    alert(res.msg)
                }else if (res.status==0){
                    alert(res.msg);
                    location.href='{% url 'fruitShop:user_login' %}';
                }
        })
    }
    </script>
{% endblock %}

练手项目/fruitShop/templates/fruitShop/base_user.html
{% extends 'fruitShop/base_buttom_top.html' %}
{% block body_content %}
{#    和用户相关的,比如用户中心,购物车公用模板#}
    {% load static %}

    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'fruitShop/images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ user_p_title }}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
    {% block body_content_inner %}

        {% endblock %}
{% endblock %}

练手项目/fruitShop/templates/fruitShop/cart.html
{% extends 'fruitShop/base_user.html' %}
{% block body_content_inner %}
    {% load static %}

<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for good in cartGoods %}
        <form action="{% url 'fruitShop:revieworder' %}" method="get">
	<ul class="cart_list_td clearfix" id="cart_id_{{ good.id }}">
		<li class="col01"><input value="{{ good.id }}" type="checkbox" name="selectme" id="check_cart_{{ good.id }}" onchange="tootal()" checked></li>
		<li class="col02"><img src="{% static 'fruitShop/upload_images/' %}{{ good.good.picture }}"></li>
		<li class="col03">{{ good.good.name }}<br><em>{{ good.good.price }}元/{{ good.good.unit }}</em></li>
		<li class="col04">{{ good.good.unit }}</li>
		<li class="col05"><span  id="good_price_{{ good.id }}">{{ good.good.price }}</span>元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" onclick="addNum_1(this,{{ good.id }})">+</a>
				<input type="text" class="num_show fl" value="{{ good.number }}" onchange="updateCartNum(this,{{ good.id }})">
				<a href="javascript:;" class="minus fl" onclick="reduceNum_1(this,{{ good.id }})">-</a>
			</div>
		</li>
		<li class="col07" id="all_cart_good_price_{{ good.id }}"></li>
		<li class="col08"><a onclick="deleteThisGood({{ good.id }})" href="javascript:;">删除</a></li>
	</ul>
{% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" onclick="selectMe(this)" checked="checked"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total_price">42.60</em><br>共计<b id="total_cont">2</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算" style="font-size:20px;color:beige;background: red;border: none;width: 100%;height: 78px;"></li>
	</ul>
</form>
{% endblock %}
{% block js %}
    <script>
    tootal()
    function tootal() {
        var total=0
        var total_count=0
        $('.col07').each(function () {
            checked=$(this).prev().prev().prev().prev().prev().prev().find('input')[0].checked
            if(checked){
                count=$(this).prev().find('input').val()
                price=$(this).prev().prev().text()
                total0=parseFloat(count)*parseFloat(price)
                $(this).text(total0.toFixed(2)+' 元')
                total+=total0
                total_count++
            }
        })
        $("#total_price").text(total)
        $("#total_cont").text(total_count)
    }
        function addNum_1(obj,id) {
            $(obj).next().val(parseInt($(obj).next().val())+1)
            updateCartNum($(obj).next()[0],id)
            tootal()
        }
        function reduceNum_1(obj,id) {
            if(parseInt($(obj).prev().val())>1){
                $(obj).prev().val(parseInt($(obj).prev().val())-1)
                updateCartNum($(obj).prev()[0],id)
                tootal()
            }
        }
        
        function updateCartNum(obj,id) {
             var number=parseInt($(obj).val());
                $.post('{% url 'fruitShop:editcart' %}',{
                    'id':id,
                    'number':number,
                    'csrfmiddlewaretoken':'{{ csrf_token }}'
                },function (res) {
                    if(res.status){
                        $(obj).val(number);
                        tootal()
                    }
                })
        }
        function selectMe(obj) {
            if($(obj)[0].checked==true){
                select()
            }else{
                noselect()
            }
            tootal()
        }

          /*全选，取消全选*/
        var checkall=document.getElementsByName("selectme");
        //全选
        function select(){
          for(var $i=0;$i<checkall.length;$i++){
            checkall[$i].checked=true;
          }
        };
        //全不选
        function noselect(){
          for(var $i=0;$i<checkall.length;$i++){
            checkall[$i].checked=false;
          }
        }
        //删除购物车中的商品
        function deleteThisGood(id) {
            if(confirm('确定要删除吗?')){
                $.post('{% url 'fruitShop:editcart' %}',{
                    'id':id,
                    'delete':1,
                    'csrfmiddlewaretoken':'{{ csrf_token }}'
                },function (res) {
                    if(res.status){
                        $("#cart_id_"+id).remove()
                        tootal()
                    }
                })
            }
        }
    </script>
{% endblock %}

练手项目/fruitShop/templates/fruitShop/detail.html
{% extends 'fruitShop/base_goods.html' %}

{% block body_content_inner %}
{% load static %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for cate in categories %}
					<li><a href="{% url 'fruitShop:list' cate.id 1 1 %}" class="{{ cate.className }}">{{ cate.title }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="/">全部分类</a>
		<span>></span>
		<a href="{% url 'fruitShop:list' good.category_id 1 1 %}">{{ cate }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img width="100%" src="{% static 'fruitShop/upload_images/' %}{{ good.picture }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good.name }}</h3>
			<p>{{ good.intro }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good.price }}</em></span>
				<span class="show_unit">单  位：{{ good.unit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：{{ good.number }}</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" id="goods_num_show" value="1">
					<a href="javascript:;" class="add fr" onclick="addNum()">+</a>
					<a href="javascript:;" class="minus fr" onclick="reduceNum()">-</a>
				</div>
			</div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" onclick="addCart_1({{ good.id }})" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>
{#onclick="addCart({{ good.id }})" #}
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for t in t_goods %}
					<li>
						<a href="{% url 'fruitShop:detail' t.id %}"><img src="{% static 'fruitShop/upload_images/' %}{{ t.picture }}"></a>
						<h4><a href="#">{{ t.name }}</a></h4>
						<div class="prize">￥{{ t.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>
                    {{ good.content|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
<div class="add_jump"></div>

{% endblock %}

{% block js %}
<script type="text/javascript">
        function addNum() {
            $("#goods_num_show").val(parseInt($("#goods_num_show").val())+1)
        }
        function reduceNum() {
            if($("#goods_num_show").val()>1){
                $("#goods_num_show").val(parseInt($("#goods_num_show").val())-1)
            }
        }
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;
		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
        function addCart_1(good_id) {
		    number=parseInt($("#goods_num_show").val());
            $.post('{% url 'fruitShop:addcart' %}',
                {'id':good_id,'number':number,'csrfmiddlewaretoken':'{{ csrf_token }}'},
                function(res){
                    if(res.status==1){
                        $(".add_jump").stop().animate({
                            'left': $to_y+7,
                            'top': $to_x+7},
                            "fast", function() {
                                $(".add_jump").fadeOut('fast',function(){
                                    $('#show_count').text(parseInt($('#show_count').text())
                                        +parseInt($("#goods_num_show").val()));
                                });

                        });
                    }else if(res.status==3){
                        alert(res.msg)
                    }else if (res.status==0){
                        alert(res.msg);
                        location.href='{% url 'fruitShop:user_login' %}';
                    }
            })
        }
	</script>
{% endblock %}