练手项目/fruitShop/fruitShop/urls.py
# coding=utf-8

from django.conf.urls import url
import views
from views import *

urlpatterns = [
    url(r'^user/register$', views.user_register, name='user_register'),
    url(r'^user/user_exist$', views.user_exist, name='user_exist'),
    url(r'^user/login$', views.user_login, name='user_login'),
    url(r'^user/info$', views.user_info, name='user_info'),
    url(r'^user/order/(\d*)$', views.user_order, name='user_order'),
    url(r'^user/site$', views.user_site, name='user_site'),
    url(r'^user/logout', views.user_logout, name='user_logout'),

    url(r'^$', views.index, name='index'),
    url(r'^list/(\d+)/(\d*)/(\d*)$', views.list, name='list'),
    url(r'^detail/(\d+)$', views.detail, name='detail'),

    url(r'^mycart$', views.cart, name='cart'),
    url(r'^addcart$', views.addCart, name='addcart'),
    url(r'^getcartcount$', views.getMyCartCount, name='getcartcount'),
    url(r'^editcart$', views.editCartGood, name='editcart'),
    url(r'^revieworder$', views.reviewOrder, name='revieworder'),
    url(r'^orderhandle$', views.orderHandle, name='orderhandle'),
    url(r'^pay/(\d+)$', views.pay, name='pay'),
    url(r'^search/',MySearchView())
]

练手项目/fruitShop/myShop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('fruitShop.urls',namespace='fruitShop')),
    url(r'^tinymce',include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
]

练手项目/fruitShop/fruitShop/models.py
# coding=utf-8
from django.db import models
from tinymce.models import HTMLField


# 用户模型
class UserInfo(models.Model):
    nickname = models.CharField(max_length=10)
    password = models.CharField(max_length=40)
    email = models.CharField(max_length=30)
    phone = models.CharField(max_length=11, default='')
    # 收件人
    shou_people = models.CharField(max_length=10, default='')
    # 收货地址,省,市,县,具体地址
    p_c_a_detail = models.CharField(max_length=100, default='')
    # 邮编
    zip_code = models.IntegerField(default=0)


# 商品分类
class GoodsCategory(models.Model):
    title = models.CharField(max_length=10)
    # 封面
    cover = models.ImageField(upload_to='category')
    # css 类名
    className = models.CharField(max_length=10, default='')
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.title.encode('utf-8')


# 商品
class GoodsInfo(models.Model):
    name = models.CharField(max_length=20)
    picture = models.ImageField(upload_to='goods')
    # 单位
    unit = models.CharField(default='500g', max_length=20)
    # 点击数,热度
    click = models.IntegerField(default=0)
    # 简介
    intro = models.CharField(max_length=200)
    number = models.IntegerField(default=0)
    # 介绍
    content = HTMLField()
    # 分类
    category = models.ForeignKey(GoodsCategory)
    # 价格
    price = models.DecimalField(max_digits=5, decimal_places=2)
    # 推荐
    isTop = models.BooleanField(default=False)
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.name.encode('utf-8')


# 首页banner
class Banner(models.Model):
    title = models.CharField(max_length=20)
    banner = models.ImageField(upload_to='banner')
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.title.encode('utf-8')


# 订单表
class OrderInfo(models.Model):
    # 订单号
    id = models.CharField(max_length=30, primary_key=True)
    # 用户
    user = models.ForeignKey(UserInfo)
    # 日期
    date = models.DateTimeField(auto_now=True)
    # 是否支付
    isPay = models.BooleanField(default=False)
    # 支付金额
    totalPrice = models.DecimalField(max_digits=6, decimal_places=2)
    # 收货地址
    address = models.CharField(max_length=100, default='')


# 订单详情表
class OrderDetail(models.Model):
    # 商品
    goods = models.ForeignKey(GoodsInfo)
    # 订单
    order = models.ForeignKey(OrderInfo)
    # 单价
    price = models.DecimalField(max_digits=5, decimal_places=2)
    # 数量
    number = models.IntegerField(default=0)


# 购物车
class ShopCart(models.Model):
    user = models.ForeignKey(UserInfo)
    good = models.ForeignKey(GoodsInfo)
    number = models.IntegerField(default=0)

练手项目/fruitShop/fruitShop/views.py
# coding=utf-8
from django.shortcuts import render, redirect
from models import *
from hashlib import sha1
from django.http import JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import *
from decorators import *
from django.db.models import Sum
from django.db import transaction
import datetime
from decimal import Decimal
from haystack.views import SearchView


# 用户注册
def user_register(request):
    if request.method == 'POST':
        # 接受用户输入
        user_name = request.POST.get('user_name')
        email = request.POST.get('email')
        pwd = request.POST.get('pwd')
        cpwd = request.POST.get('cpwd')
        # 判断两次密码是否相等
        if pwd != cpwd:
            return redirect(reverse('fruitShop:user_register'))
        # 密码加密
        s1 = sha1()
        s1.update(cpwd)
        password = s1.hexdigest()
        # 保存数据
        UserInfo.objects.create(nickname=user_name, password=password, email=email)
    return render(request, 'fruitShop/user/register.html', {'title': '用户注册'})


# 检测用户名时候已存在
def user_exist(request):
    if request.is_ajax():
        nickname = request.GET.get('nickname')
        count = UserInfo.objects.filter(nickname=nickname).count()
        return JsonResponse({'count': count})


# 用户登录
def user_login(request):
    if request.method == 'POST':
        nickname = request.POST.get('username', '')
        password = request.POST.get('pwd', '')
        remember = request.POST.get('remember', 0)
        # 查询用户是否存在
        user = UserInfo.objects.filter(nickname=nickname)
        if len(user) == 1:
            s1 = sha1()
            s1.update(password)
            if s1.hexdigest() == user[0].password:
                # 密码验证成功
                to_url = request.COOKIES.get('to_url', '/')
                redirect = HttpResponseRedirect(to_url)
                if remember:
                    # 记住用户名
                    redirect.set_cookie('nickname', nickname)

                # 保存session用户信息
                request.session['user_id'] = user[0].id
                request.session['nickname'] = nickname
                # 进行跳转
                return redirect
            else:
                context = {'nickname_error': '', 'password_error': '密码错误', 'nickname': nickname, 'pwd': password}
        else:
            context = {'nickname_error': '用户名不存在', 'password_error': '', 'nickname': nickname, 'pwd': password}
        return render(request, 'fruitShop/user/login.html', context)
    nickname = request.COOKIES.get('nickname', '')
    return render(request, 'fruitShop/user/login.html',
                  {'nickname_error': '', 'password_error': '', 'nickname': nickname, 'pwd': '', 'title': '用户登录'})


# 退出登录
def user_logout(request):
    request.session.flush()
    return redirect('/')


# 用户信息
@check_user_login
def user_info(request):
    good_ids = request.COOKIES.get('good_ids', '')
    if good_ids != '':
        good_ids_list = good_ids.split(',')
    else:
        good_ids_list = []
    viewGoods = GoodsInfo.objects.filter(id__in=good_ids_list)
    user_id = request.session.get('user_id', 0)
    user = UserInfo.objects.filter(pk=user_id)
    context = {'userInfo': user[0], 'title': '用户中心-个人信息', 'viewGoods': viewGoods, 'user_p_title': '用户中心'}
    return render(request, 'fruitShop/user/info.html', context)


# 用户订单
@check_user_login
def user_order(request, p):
    if p == '':
        p = 1
    user_id = request.session.get('user_id')
    orders = OrderInfo.objects.filter(user_id=user_id).order_by('-id')
    orderDetails = []
    for order in orders:
        detail = OrderDetail.objects.filter(order_id=order.id)
        order.detail = detail
        orderDetails.append(order)
    print(orderDetails)
    paginator = Paginator(orderDetails, 3)
    page = paginator.page(int(p))
    context = {'title': '用户中心-订单', 'user_p_title': '用户中心', 'page': page, 'p_index': p}
    return render(request, 'fruitShop/user/order.html', context)


# 用户收货地址
@check_user_login
def user_site(request):
    user_id = request.session.get('user_id', 0)
    user = UserInfo.objects.filter(pk=user_id)[0]
    if request.method == 'POST':
        shou_people = request.POST.get('shou_people')
        phone = request.POST.get('phone')
        zip_code = request.POST.get('zip_code')
        user.shou_people = shou_people
        user.phone = phone
        user.p_c_a_detail = request.POST.get('address', '')
        if zip_code == '':
            zip_code = 0
        user.zip_code = zip_code
        user.save()
    context = {'title': '用户中心-收货地址', 'userInfo': user, 'user_p_title': '用户中心'}
    return render(request, 'fruitShop/user/site.html', context)


# 首页
def index(request):
    # 所有的分类
    categories = GoodsCategory.objects.all()[:6]
    data = []
    for cate in categories:
        # 根据分类查询商品
        this_good = cate.goodsinfo_set
        if len(this_good.order_by('-click')) > 0:
            data.append({
                'cate': cate,  # 分类
                'goods': this_good.order_by('-click')[:4],  # 分类下的商品
                's_goods': this_good.filter(isTop=1).values('id', 'name')[:4]
            })
    banners = Banner.objects.all()
    context = {'title': '商城首页', 'categories': categories, 'data': data, 'banners': banners}
    return render(request, 'fruitShop/index.html', context)


# 商品列表
def list(request, c_id, p_index, sort):
    cates = __getCategory()
    newGoods = GoodsInfo.objects.filter(category_id=c_id).order_by('-id')[:5]
    if sort == '2':
        sort_by = 'price'
    elif sort == '3':
        sort_by = '-click'
    else:
        sort_by = 'id'
    goods = GoodsInfo.objects.filter(category_id=c_id).order_by(sort_by)
    paginator = Paginator(goods, 30)
    page = paginator.page(int(p_index))
    context = {
        'title': '商品列表',
        'c_id': c_id,
        'sort': sort,
        'page': page,
        'categories': cates,
        'newGoods': newGoods
    }
    return render(request, 'fruitShop/list.html', context)


# 商品详情
def detail(request, id):
    cates = __getCategory()
    good = GoodsInfo.objects.filter(pk=id)[0]
    good.click += 1
    good.save()
    t_goods = GoodsInfo.objects.filter(category_id=good.category_id)[:3]
    cate = GoodsCategory.objects.filter(pk=good.category_id)[0].title
    # 添加商品浏览记录
    good_ids = request.COOKIES.get('good_ids', '')
    good_id = '%d' % good.id
    if good_ids != '':
        good_ids_list = good_ids.split(',')
        # 如果没有就插入一个
        if good_ids_list.count(good_id) == 0:
            good_ids_list.insert(0, good_id)
        if len(good_ids_list) > 5:
            # 删除最后一个
            del good_ids_list[5]
        good_ids = ','.join(good_ids_list)
    else:
        # 添加第一条
        good_ids = good_id
    context = {
        'title': '商品详情',
        'categories': cates,
        'id': id,
        'good': good,
        'cate': cate,
        't_goods': t_goods
    }
    responce = render(request, 'fruitShop/detail.html', context)
    # 保存浏览历史到cookie
    responce.set_cookie('good_ids', good_ids)
    return responce


# 获取分类
def __getCategory():
    categories = GoodsCategory.objects.filter(isDelete=0)
    cates = []
    for cate in categories:
        if len(cate.goodsinfo_set.all()) > 0:
            cates.append(cate)
    return cates


# 购物车
@check_user_login
def cart(request):
    user_id = request.session.get('user_id')
    cartGoods = ShopCart.objects.filter(user_id=user_id)
    context = {'title': '我的购物车', 'cartGoods': cartGoods, 'user_p_title': '我的购物车'}
    return render(request, 'fruitShop/cart.html', context)


# 添加商品到购物车
def addCart(request):
    user_id = request.session.get('user_id', '')
    if user_id == '':
        return JsonResponse({'status': 0, 'msg': '您未登录'})
    else:
        good_id = request.POST.get('id', 0)
        goods_number = GoodsInfo.objects.get(pk=good_id).number
        number = int(request.POST.get('number', 1))
        if goods_number >= number:
            this_goods = ShopCart.objects.filter(good_id=good_id)
            if len(this_goods) == 1:
                this_good = this_goods[0]
                this_good.number += number
                this_good.save()
            else:
                ShopCart.objects.create(user_id=user_id, number=1, good_id=good_id)
            return JsonResponse({'status': 1, 'msg': '添加成功'})
        else:
            return JsonResponse({'status': 3, 'msg': '库存不足'})


# 获取购物车数量
def getMyCartCount(request):
    user_id = request.session.get('user_id', '')
    if user_id == '':
        return JsonResponse({'count': 0})
    else:
        count = ShopCart.objects.filter(user_id=user_id).aggregate(Sum('number'))
        return JsonResponse({'count': count['number__sum']})


# 编辑购物车
@check_user_login
def editCartGood(request):
    id = request.POST.get('id', 0)
    if request.POST.get('delete', 0) == '1':
        this_chart_good = ShopCart.objects.get(pk=id)
        this_chart_good.delete()
        return JsonResponse({'status': 1, 'msg': '删除完成'})
    if request.POST.get('number', 0) != 0:
        number = request.POST.get('number', 0)
        this_chart_good = ShopCart.objects.get(pk=id)
        this_chart_good.number = number
        this_chart_good.save()
        return JsonResponse({'status': 1, 'msg': '修改完成'})


# 预览订单
@check_user_login
def reviewOrder(request):
    address = UserInfo.objects.get(pk=request.session.get('user_id')).p_c_a_detail
    context = {'address': address, 'title': '确认订单', 'user_p_title': '确认订单'}
    cart_ids = request.GET.getlist('selectme')
    carts = ShopCart.objects.filter(id__in=cart_ids)
    context['carts'] = carts
    context['cart_ids'] = '_'.join(cart_ids)
    return render(request, 'fruitShop/review_order.html', context)


# 启用数据库事务操作
@transaction.atomic()
@check_user_login
def orderHandle(request):
    # 记录当前操作点
    tran_id = transaction.savepoint()
    # /接受要支付的购物车id
    cart_ids = request.GET.get('cart_ids')
    try:
        order = OrderInfo()
        now = datetime.datetime.now()

练手项目/fruitShop/templates/fruitShop/user/info.html
{% extends 'fruitShop/base_user.html' %}
{% block body_content_inner %}
{% load static %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'fruitShop:user_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'fruitShop:user_order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'fruitShop:user_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ userInfo.nickname }}</li>
							<li><span>联系方式：</span>{{ userInfo.phone }}</li>
							<li><span>联系地址：</span>{{ userInfo.p_c_a_detail }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for good in viewGoods %}
				<li>
					<a href="{% url 'fruitShop:detail' good.id %}"><img src="{% static 'fruitShop/upload_images/' %}{{ good.picture }}"></a>
					<h4><a href="{% url 'fruitShop:detail' good.id %}">{{ good.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.price }}</span>
						<span class="unit">{{ good.price }}/{{ good.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                        {% endfor %}
			</ul>
		</div>
		</div>
	</div>

{% endblock %}

练手项目/fruitShop/templates/fruitShop/user/login.html
{% extends 'fruitShop/base_buttom.html' %}
{% load static %}
{% block body %}

	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="{% static 'fruitShop/images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'fruitShop:user_register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{% url 'fruitShop:user_login' %}">
						<input type="text" name="username" class="name_input" value="{{ nickname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ pwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="javascript:;">忘记密码</a>
						</div>
                        {% csrf_token %}
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block js %}

<script>
        if('{{ nickname_error }}'){
            $(".user_error").html('{{ nickname_error }}').show()
        }
        if('{{ password_error }}'){
            $(".pwd_error").html('{{ password_error }}').show()
        }

        $('.name_input').blur(function() {
            if($(this).val().length==0){
                $(".user_error").html('用户名不能为空').show();
            }
        });
        $('.pass_input').blur(function() {
            if($(this).val().length==0){
                $(".pwd_error").html('密码不能为空').show();
            }
        });
    </script>

{% endblock %}

练手项目/fruitShop/templates/fruitShop/user/order.html
{% extends 'fruitShop/base_user.html' %}
{% block body_content_inner %}
    {% load static %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'fruitShop:user_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'fruitShop:user_order' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'fruitShop:user_site' %}">· 收货地址</a></li>
			</ul>
		</div>
        {% for order in page %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.date }}</li>
					<li class="col02">订单号：{{ order.id }}</li>
					<li class="col02 stress">
                        {% if order.isPay == 1 %}
                            已支付
                            {% else %}
                            未支付
                        {% endif %}
                        </li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for good in order.detail %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'fruitShop/upload_images/' %}{{ good.goods.picture }}"></li>
									<li class="col02">{{  good.goods.name  }}<em>{{ good.goods.price }}元/{{ good.goods.unit }}</em></li>
									<li class="col03">{{ good.number }}件</li>
									<li class="col04">{{ good.price }}元</li>
								</ul>
                                    {% endfor %}
							</td>
							<td width="15%">{{ order.totalPrice }}元</td>
                        {% if order.isPay == 1 %}
							<td width="15%">以付款</td>
                            <td width="15%"><a href="#" class="oper_btn">查物流</a></td>

                            {% else %}
                            <td width="15%">待付款</td>
							<td width="15%"><a href="{% url 'fruitShop:pay' order.id %}" class="oper_btn">去付款</a></td>
                        {% endif %}
						</tr>
					</tbody>
				</table>
{% endfor %}

    <div class="pagenation">
                {% if page.has_previous %}
				<a href="{% url 'fruitShop:user_order' page.previous_page_number %}"><上一页</a>
                {% endif %}

                {% for p_index in page.paginator.page_range %}
                    {% if p_index == page.number %}
                        <a href="javascript:;" class="active">{{ p_index }}</a>
                    {% else %}
                        <a href="{% url 'fruitShop:user_order' p_index %}">{{ p_index }}</a>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <a href="{% url 'fruitShop:user_order' page.next_page_number %}">下一页></a>
                {% endif %}
			</div>

		</div>
	</div>

{% endblock %}

练手项目/fruitShop/templates/fruitShop/user/register.html
{% extends 'fruitShop/base_buttom.html' %}
{% load static %}
{% block head %}
	<script type="text/javascript" src="{% static 'fruitShop/js/register.js' %}"></script>
{% endblock %}
{% block body %}
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a href="/" class="reg_logo"><img src="{% static 'fruitShop/images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'fruitShop:user_login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form id="reg_form" action="{% url 'fruitShop:user_register' %}" method="post">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
                    {% csrf_token %}
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock %}

练手项目/fruitShop/templates/fruitShop/user/site.html
{% extends 'fruitShop/base_user.html' %}
{% block body_content_inner %}
{% load static %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'fruitShop:user_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'fruitShop:user_order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'fruitShop:user_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ userInfo.p_c_a_detail }}（{{ userInfo.shou_people }} 收） {{ userInfo.phone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url 'fruitShop:user_site' %}" method="post">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="shou_people" value="{{ userInfo.shou_people }}">
						</div>
						<div class="form_group form_group2">
							<label>收货地址：</label>
							<textarea name="address" class="site_area">{{ userInfo.p_c_a_detail }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="number" value="{{ userInfo.zip_code }}" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" value="{{ userInfo.phone }}" name="phone">
						</div>
{% csrf_token %}
						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock %}